name: Close wontfix issues

on:
  issues:
    types: [labeled]

jobs:
  close-issue:
    if: github.event.label.name == 'wontfix'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: This issue has been automatically closed because it was labeled as 'wontfix'.
